#
# Please don't change this file unless you know what you are doing.
#

language: objective-c
osx_image: xcode7.3

# We're using the 'script' section here to drive the tests instead of
# xcode_project/xcode_scheme provided by Travis. This is because we
# can better address non-trivial scenarios.
script:
#  xctool -project emotly/emotly.xcodeproj -scheme emotly -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6 Plus' build test ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - set -o pipefail && xcodebuild clean -project Emotly/Emotly.xcodeproj -scheme Emotly -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty
  - set -o pipefail && xcodebuild build -project Emotly/Emotly.xcodeproj -scheme Emotly -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty
  - set -o pipefail && xcodebuild test -project Emotly/Emotly.xcodeproj -scheme Emotly -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty

